title: Jijith MS
author: Jijith MS
email: jijith1309@gmail.com
description: >-
  Senior .NET Developer from Kochi, Kerala. Building with .NET Core, Angular & Azure. Exploring GenAI.
baseurl: ""
url: "https://jijith1309.github.io"
year: 2025

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
