title: My Portfolio
email: your.email@example.com
description: >-
  This is my personal portfolio website built with Jekyll and GitHub Pages.
baseurl: "" # for user.github.io, leave this empty
url: "https://jijith1309.github.io" # change to your GitHub Pages URL

theme: minima

plugins:
  - jekyll-feed
